### ISSUE TITLE
"missing" workspace leads to cryptic error

### ISSUE THREAD

**Issue by ekiefl** [roboflow/roboflow-python#140]
## Problem

It seems roboflow fails to find a workspace that exists. Here is my script:

```python
from roboflow import Roboflow
rf = Roboflow(api_key="mykey")
project = rf.workspace("PoolTool")
```

where `mykey` is my private key. Here's the error:

```
Traceback (most recent call last):
  File "roboflow_test.py", line 3, in <module>
    project = rf.workspace("PoolTool")
  File "/Users/evan/anaconda3/envs/poolml/lib/python3.8/site-packages/roboflow/__init__.py", line 279, in workspace
    print(list_projects)
  File "/Users/evan/anaconda3/envs/poolml/lib/python3.8/site-packages/roboflow/core/workspace.py", line 28, in __init__
    workspace_info = info["workspace"]
KeyError: 'workspace'
```

The workspace definitely exists though. I've down some of the legwork and interrogated the code. This function call returns an uncaught response error:

https://github.com/roboflow/roboflow-python/blob/02b717f453e95c5cdef8a817914a46f5fd6771a8/roboflow/__init__.py#L273-L275

```
{'error': {'message': 'Unsupported get request. Workspace with ID `PoolTool` does not exist or cannot be loaded due to missing permissions.', 'type': 'GraphMethodException', 'hint': 'You can see your available workspaces by issuing a GET request to /workspaces'}}
```

Upon the advice of the response, I tried the following request:

```
requests.get(API_URL + "/workspaces" + "?api_key=" + self.api_key).json()
```

But I got this:

```
{'error': {'message': 'Unsupported get request. Workspace with ID `workspaces` does not exist or cannot be loaded due to missing permissions.', 'type': 'GraphMethodException', 'hint': 'You can see your available workspaces by issuing a GET request to /workspaces'}}
```

So probably I have missing permissions? This is an unsubscribed, private workspace.

## Versioning

Roboflow 1.0.5
Python 3.8.10
macOS 13.3.1

**Comment by ekiefl** [comment]
Ahh I see. Thanks to the amazing website, I found a code snippet generator:

<img width="591" alt="image" src="https://user-images.githubusercontent.com/8688665/233163874-5b79c4e1-0596-4ba8-94a1-4341b2ce2bc8.png">

The difference is capitalization. I'll leave this open so that you guys can decide whether this is a feature or a bug, but my issue is officially resolved :)

**Comment by mo-traor3-ai** [comment]
> Ahh I see. Thanks to the amazing website, I found a code snippet generator:
> 
> <img alt="image" width="591" src="https://user-images.githubusercontent.com/8688665/233163874-5b79c4e1-0596-4ba8-94a1-4341b2ce2bc8.png">
> 
> The difference is capitalization. I'll leave this open so that you guys can decide whether this is a feature or a bug, but my issue is officially resolved :)

This is by design. When in doubt, the export code generated when selecting "Export Dataset" will give you a reliable dataset export code.
<img width="265" alt="image" src="https://user-images.githubusercontent.com/89935638/233180923-fa0a020a-4d61-4ebe-b404-b2717b3ffa42.png">

The other option is using the Deploy Tab within your own projects, and the API Docs Tab on Universe projects.
<img width="880" alt="image" src="https://user-images.githubusercontent.com/89935638/233180894-2ab2c7ed-de90-4fc8-aa50-ff8a563127bd.png">


<img width="729" alt="image" src="https://user-images.githubusercontent.com/89935638/233180835-d7caf60d-b4fe-445e-814c-5ca53251fe5f.png">

**Comment by mo-traor3-ai** [comment]
@ekiefl good suggestion

One thing I know we already have is the ability to list projects in a specified workspace, and associated versions.
* List all projects in a workspace (workspace is set/tied to each Private API Key)
```
from roboflow import Roboflow

rf = Roboflow(api_key="mykey")
workspace = rf.workspace()
workspace_projects = workspace.list_projects()
print(workspace_projects) # prints a list containing all project-id's for projects in the workspace
```

* List all versions in a workspace (workspace is set/tied to each Private API Key)
1.
```
from roboflow import Roboflow

rf = Roboflow(api_key="mykey")
workspace = rf.workspace()
project = workspace.project("insert-project-id")
all_versions = project.list_versions()
print(all_versions) # prints a list containing all version#'s for the project in the workspace with the specified project-id
```
2.
```
from roboflow import Roboflow

rf = Roboflow(api_key="mykey")
workspace = rf.workspace()
project = workspace.project("insert-project-id")
all_version_objs = project.versions()
print(all_version_objs) # prints a list containing all Version objects for the project in the workspace with the specified project-id
```

Additionally, each Private API Key is to analogous to each individual workspace. So you can actually load the workspace like so:
```
from roboflow import Roboflow

rf = Roboflow(api_key="mykey")
workspace = rf.workspace()
```

Finally, there is a secondary workspace credential option, which is the new `roboflow.login()` method. You'll receive a link to a window, like when using the CLI, to view all workspaces you're currently in. This will include the workspace-id's.
* [roboflow-python/roboflow/__init__.py, line 74](https://github.com/roboflow/roboflow-python/blob/1c37df31d4f84dc15681af895b92c8ab0ea13e1d/roboflow/__init__.py#L74)
* Roboflow CLI - Blog Post - [feature release announcement](https://blog.roboflow.com/roboflow-command-line-interface-for-computer-vision/) | [Roboflow CLI Blog Post from Launch Week](https://blog.roboflow.com/roboflow-api-cli-features/) | [Roboflow CLI - Documentation](https://docs.roboflow.com/command-line-interface) | [Roboflow CLI - GitHub repo](https://github.com/roboflow/roboflow-cli)
```
#log into Roboflow

import roboflow
# roboflow.login(workspace=None, force=False)
# workspace="workspace-id" - allows you to login and get credentials for a specific `workspace-id`
# force=True brings up CLI window to re-auth to workspace, or auth to a new one
roboflow.login()
```
* Click the link present in `visit https://app.roboflow.com/auth-cli to get your authentication token.`
* Be sure you only have the workspace you want to load/use checked off before you select `Generate Token`
<img width="571" alt="image" src="https://user-images.githubusercontent.com/89935638/233238646-da55c4d4-ac69-4962-8656-06e55c73526b.png">
<img width="991" alt="image" src="https://user-images.githubusercontent.com/89935638/233238793-e6839aea-4de5-4287-b8ee-6328a2e2ec70.png">

^^ note the `workspace-id` present in the right-hand column
<img width="1034" alt="image" src="https://user-images.githubusercontent.com/89935638/233237827-09368343-8c7c-479f-8c55-1b8a52dbf8df.png">

<img width="802" alt="image" src="https://user-images.githubusercontent.com/89935638/233237806-b337d9c9-882f-4eca-81d2-7ac389e3f4bf.png">
